spring.application.name=odontoplus

#Configuração Banco de Dados

spring.datasource.url=jdbc:h2:mem:odontoplus
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Configurar o flyway
spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration